### PR TITLE
Completed javascript-typing-tutor - Lisa Nguyen

### PR DESCRIPTION
**Pull request by lisa-t-nguyen**
chrome_aGQlPHP40L

### CODE REVIEW

**Review by Zhiwutian — CHANGES_REQUESTED** [review]
Great functionality! The only thing to update is that you only want the underline for the current character.

**Comment by lisa-t-nguyen** [comment]
> Great functionality! The only thing to update is that you only want the underline for the current character.

Gotcha!! I missed that!

**Comment by lisa-t-nguyen** [comment]
chrome_f3ED8gdGL7

**Review by Zhiwutian — APPROVED** [review]
👍🏼

**Pull request merged**
